// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhY14itxbiVjIrnZ69wnZ3qrL9T0apPAc',
    appId: '1:845616676003:web:621a18a47d59a6266cd316',
    messagingSenderId: '845616676003',
    projectId: 'flutterbloc-c4f97',
    authDomain: 'flutterbloc-c4f97.firebaseapp.com',
    storageBucket: 'flutterbloc-c4f97.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTObj_7pVdEpUVW0QeDcTkfRNStFJ2kLk',
    appId: '1:845616676003:android:588c066a83f2b5a76cd316',
    messagingSenderId: '845616676003',
    projectId: 'flutterbloc-c4f97',
    storageBucket: 'flutterbloc-c4f97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCefHP9vOj4c3teGVY59FAj7uGUmc_K9_U',
    appId: '1:845616676003:ios:ae92c2617b8ffdd46cd316',
    messagingSenderId: '845616676003',
    projectId: 'flutterbloc-c4f97',
    storageBucket: 'flutterbloc-c4f97.appspot.com',
    iosClientId: '845616676003-2i8c7qpuatqmj597v344pa14ld3l4sid.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStateBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCefHP9vOj4c3teGVY59FAj7uGUmc_K9_U',
    appId: '1:845616676003:ios:ae92c2617b8ffdd46cd316',
    messagingSenderId: '845616676003',
    projectId: 'flutterbloc-c4f97',
    storageBucket: 'flutterbloc-c4f97.appspot.com',
    iosClientId: '845616676003-2i8c7qpuatqmj597v344pa14ld3l4sid.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStateBloc',
  );
}
